# Configuration for TM-Vec and ProstT5 backbone model

defaults:
  - default

# Specific target for TM-Vec and ProstT5 model
target: backbones.tm_vec_and_prostt5.model.TMVecAndProstT5Model

# Model-specific parameters
model_paths:
  prostt5_model: 'Rostlab/ProstT5'
  tm_vec_checkpoint: "weights/TM-Vec/tm_vec_cath_model.ckpt"
  tm_vec_config: "weights/TM-Vec/tm_vec_cath_model_params.json"

# Output configuration
embedding_types:
  - "ProstT5"
  - "TM-Vec"

levels:
  - "AA"  # Amino acid (residue) level
  - "PR"  # Protein level